"""empty message

Revision ID: f07974cc1d32
Revises: 
Create Date: 2018-12-03 15:06:37.337340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07974cc1d32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manuf',
    sa.Column('manufId', sa.Integer(), nullable=False),
    sa.Column('manufName', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('manufId')
    )
    op.create_index(op.f('ix_manuf_manufName'), 'manuf', ['manufName'], unique=True)
    op.create_table('user',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('med_stock',
    sa.Column('medId', sa.Integer(), nullable=False),
    sa.Column('medName', sa.String(length=120), nullable=True),
    sa.Column('manufId', sa.Integer(), nullable=True),
    sa.Column('manufName', sa.String(length=120), nullable=True),
    sa.Column('availQnty', sa.Integer(), nullable=True),
    sa.Column('CO1', sa.Integer(), nullable=True),
    sa.Column('expDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['manufId'], ['manuf.manufId'], ),
    sa.ForeignKeyConstraint(['manufName'], ['manuf.manufName'], ),
    sa.PrimaryKeyConstraint('medId')
    )
    op.create_index(op.f('ix_med_stock_medName'), 'med_stock', ['medName'], unique=True)
    op.create_table('bought_by',
    sa.Column('cusId', sa.Integer(), nullable=False),
    sa.Column('cusName', sa.String(length=120), nullable=True),
    sa.Column('medId', sa.Integer(), nullable=True),
    sa.Column('buyQnty', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('CO1', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CO1'], ['med_stock.CO1'], ),
    sa.ForeignKeyConstraint(['medId'], ['med_stock.medId'], ),
    sa.PrimaryKeyConstraint('cusId')
    )
    op.create_index(op.f('ix_bought_by_cusName'), 'bought_by', ['cusName'], unique=True)
    op.create_table('manuf_stock',
    sa.Column('mStockid', sa.Integer(), nullable=False),
    sa.Column('manufId', sa.Integer(), nullable=True),
    sa.Column('availMedId', sa.Integer(), nullable=True),
    sa.Column('availMedName', sa.String(length=120), nullable=True),
    sa.Column('availManufQnty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['availMedId'], ['med_stock.medId'], ),
    sa.ForeignKeyConstraint(['availMedName'], ['med_stock.medName'], ),
    sa.ForeignKeyConstraint(['manufId'], ['manuf.manufId'], ),
    sa.PrimaryKeyConstraint('mStockid')
    )
    op.create_table('order_med_for',
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('medId', sa.Integer(), nullable=True),
    sa.Column('medName', sa.String(length=120), nullable=True),
    sa.Column('toManufId', sa.Integer(), nullable=True),
    sa.Column('wantQnty', sa.Integer(), nullable=True),
    sa.Column('byDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['medId'], ['med_stock.medId'], ),
    sa.ForeignKeyConstraint(['medName'], ['med_stock.medName'], ),
    sa.ForeignKeyConstraint(['toManufId'], ['manuf.manufId'], ),
    sa.PrimaryKeyConstraint('orderId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_med_for')
    op.drop_table('manuf_stock')
    op.drop_index(op.f('ix_bought_by_cusName'), table_name='bought_by')
    op.drop_table('bought_by')
    op.drop_index(op.f('ix_med_stock_medName'), table_name='med_stock')
    op.drop_table('med_stock')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_manuf_manufName'), table_name='manuf')
    op.drop_table('manuf')
    # ### end Alembic commands ###
